In [1]:
import torch

ft = torch.FloatTensor([[1,2],[3,4]]) #2차원의 float타입의 배열 생성
ft

tensor([[1., 2.],
        [3., 4.]])

In [2]:
lt = torch.LongTensor([[1,2],[3,4]])

lt

#LongTensor : 정수(int보다 큼)
# >> index 담을때 자주 쓰임

tensor([[1, 2],
        [3, 4]])

In [3]:
bt = torch.ByteTensor([[1, 0],
                       [0, 1]])
bt
# ByteTensor >> boolean(T/F)

tensor([[1, 0],
        [0, 1]], dtype=torch.uint8)

In [4]:
x = torch.zeros(3,2)

In [5]:
x = torch.FloatTensor(3, 2) # 3행 2열의 2차원 배열 생성
x

tensor([[7.1450e+31, 6.1970e-04],
        [2.8909e+26, 1.3672e-40],
        [4.5919e-41, 4.1478e-43]])

넘파이 호환성

In [6]:
import numpy as np

x = np.array([[1,2],[3,4]])
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [7]:
x = torch.from_numpy(x)
print(x, type(x))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


## Tensor Type-casting


In [8]:
ft

tensor([[1., 2.],
        [3., 4.]])

In [9]:
ft.long()

tensor([[1, 2],
        [3, 4]])

In [10]:
lt.float()

tensor([[1., 2.],
        [3., 4.]])

In [11]:
torch.FloatTensor([1,0]).byte()

# byte() >> 부동 소수점에서 8비트 부호 없는 정수
# float에서 정수로 바뀜

tensor([1, 0], dtype=torch.uint8)

In [12]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])

In [13]:
x

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])

In [15]:
#각 차원의 값
print(x.size())
print(x.shape)

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])


In [16]:
#몇차원인지
print(x.dim())
print(len(x.size()))

3
3


In [17]:
print(x.size(0)) #1번째 차원의 값
print(x.shape[0])

3
3


In [18]:
print(x.size(1)) # 2번째 차원의 값
print(x.shape[1])

2
2


In [20]:
print(x.size(2)) # 3번째 차원의 값
print(x.shape[2])

2
2


In [21]:
print(x.size(-1)) #3번째 차원의 값
print(x.shape[-1])

2
2
