# How to use GPU

In [29]:
import torch
import torch.nn as nn

In [30]:
print(torch.cuda.is_available())

True


## Convert to CUDA tensor: cuda()

In [31]:
x = torch.cuda.FloatTensor(2, 2)

x

tensor([[-0.2612, -0.6885],
        [ 0.6925,  0.0790]], device='cuda:0')

In [32]:
x = torch.FloatTensor(2, 2)

x
# 현재 cpu 에 있는 값

tensor([[-3.1707e+00,  4.3331e-41],
        [-3.1707e+00,  4.3331e-41]])

In [33]:
x.cuda()

tensor([[-3.1707e+00,  4.3331e-41],
        [-3.1707e+00,  4.3331e-41]], device='cuda:0')

In [34]:
d = torch.device('cuda:0')
# device 지정

In [35]:
x.cuda(device=d)

tensor([[-3.1707e+00,  4.3331e-41],
        [-3.1707e+00,  4.3331e-41]], device='cuda:0')

In [36]:
x.device

device(type='cpu')

## Convert to CUDA tensor: to()

In [37]:
x.to(device=d)

tensor([[-3.1707e+00,  4.3331e-41],
        [-3.1707e+00,  4.3331e-41]], device='cuda:0')

## Convert to CPU tensor from CUDA tensor

In [38]:
x = torch.cuda.FloatTensor(2, 2)

In [39]:
x = x.cpu()
x

tensor([[-3.1707e+00,  4.3331e-41],
        [-3.1707e+00,  4.3331e-41]])

In [40]:
d = torch.device('cpu')
print(d)

cpu


In [41]:
x = x.to(d) # d=cpu
x

tensor([[-3.1707e+00,  4.3331e-41],
        [-3.1707e+00,  4.3331e-41]])

## Move model from CPU to GPU.

In [42]:
def print_params(model):
    for p in model.parameters():
        print(p)

In [43]:
linear = nn.Linear(2, 2)

print_params(linear)
# requires_grad=True
# 해당 텐서에 대한 연산을 추적하여 역전파(backpropagation) 과정에서 자동 미분을 계산할 수 있도록 설정

Parameter containing:
tensor([[-0.0684,  0.2269],
        [ 0.6827, -0.5724]], requires_grad=True)
Parameter containing:
tensor([-0.1541,  0.5336], requires_grad=True)


In [44]:
linear = linear.cuda()

print_params(linear)
#  device='cuda:0', requires_grad=True

Parameter containing:
tensor([[-0.0684,  0.2269],
        [ 0.6827, -0.5724]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([-0.1541,  0.5336], device='cuda:0', requires_grad=True)


In [45]:
linear = linear.cpu()

print_params(linear)

Parameter containing:
tensor([[-0.0684,  0.2269],
        [ 0.6827, -0.5724]], requires_grad=True)
Parameter containing:
tensor([-0.1541,  0.5336], requires_grad=True)


In [46]:
d = torch.device('cuda:0')
linear = linear.to(d)

print_params(linear)

Parameter containing:
tensor([[-0.0684,  0.2269],
        [ 0.6827, -0.5724]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([-0.1541,  0.5336], device='cuda:0', requires_grad=True)


Note that nn.Module class does not have 'device' property.

In [47]:
# linear.device
# >>nn.Module class does not have 'device' property. 에러발생

## Tricks

In [48]:
x = torch.cuda.FloatTensor(2, 2)

In [49]:
x

tensor([[-0.1541,  0.5336],
        [ 0.6827, -0.5724]], device='cuda:0')

In [50]:
x.new(2, 2)
# 텐서(Tensor) 객체 x와 동일한 데이터 유형(dtype), 장치(device)를 가지는 새로운 2x2 텐서를 생성하는 코드

tensor([[-0.1541,  0.5336],
        [ 0.6827, -0.5724]], device='cuda:0')

In [51]:
torch.zeros_like(x)

tensor([[0., 0.],
        [0., 0.]], device='cuda:0')

In [52]:
torch.ones_like(x)

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')

In [53]:
list(linear.parameters())

[Parameter containing:
 tensor([[-0.0684,  0.2269],
         [ 0.6827, -0.5724]], device='cuda:0', requires_grad=True),
 Parameter containing:
 tensor([-0.1541,  0.5336], device='cuda:0', requires_grad=True)]

In [54]:
list(linear.parameters())[0]

Parameter containing:
tensor([[-0.0684,  0.2269],
        [ 0.6827, -0.5724]], device='cuda:0', requires_grad=True)

In [55]:
list(linear.parameters())[0].new(2, 2)

tensor([[-0.0684,  0.2269],
        [ 0.6827, -0.5724]], device='cuda:0')