# Mean Square Error (MSE) Loss

In [16]:
import torch

$$
\text{MSE}(\hat{x}_{1:N}, x_{1:N})=\frac{1}{N\times{n}}\sum_{i=1}^{N}{||x_i-\hat{x}_i||_2^2}
$$

In [17]:
def mse(x_hat, x):
    # |x_hat| = (batch_size, dim)
    # |x| = (batch_size, dim)
    y = ((x - x_hat)**2).mean()
    
    return y

In [18]:
x = torch.FloatTensor([[1, 1],
                       [2, 2]])
x_hat = torch.FloatTensor([[0, 0],
                           [0, 0]])

print(x)
print()
print(x_hat)
print()
print(x.size(), x_hat.size())

tensor([[1., 1.],
        [2., 2.]])

tensor([[0., 0.],
        [0., 0.]])

torch.Size([2, 2]) torch.Size([2, 2])


In [19]:
mse(x_hat, x)

tensor(2.5000)

## Predefined MSE in PyTorch

In [20]:
import torch.nn.functional as F
# 함수

In [21]:
F.mse_loss(x_hat, x)

tensor(2.5000)

In [22]:
F.mse_loss(x_hat, x, reduction='sum')
# reduction='sum': 손실 값을 계산하는 방식을 설정하는 인자
# >> 'sum' 설정 시 모든 오차의 제곱 값을 단순히 합산

tensor(10.)

In [23]:
F.mse_loss(x_hat, x, reduction='none')
# 차원 축소를 안하겠다는 의미 
# 각 요소별 오차의 제곱 값을 계산하여 텐서 형태로 반환 

tensor([[1., 1.],
        [4., 4.]])

In [24]:
import torch.nn.functional as F

x_hat = torch.tensor([1.5, 3.0, 2.2]) 
x = torch.tensor([1.0, 2.5, 2.8])

loss_ = F.mse_loss(x_hat, x)
loss = F.mse_loss(x_hat, x, reduction='sum')

print(loss_)
print()
print(loss) # 0.2867 * 3

tensor(0.2867)

tensor(0.8600)


In [25]:
0.2867 * 3

0.8601000000000001

In [29]:
import torch.nn.functional as F

x_hat = torch.tensor([1.5, 3.0, 2.2])
x = torch.tensor([1.0, 2.5, 2.8])

loss_ = F.mse_loss(x_hat, x)
loss = F.mse_loss(x_hat, x, reduction='none') 

print(loss_)
print(loss) # tensor([0.2500, 0.2500, 0.3600])

tensor(0.2867)
tensor([0.2500, 0.2500, 0.3600])


In [26]:
import torch.nn as nn 
# 객체 

In [27]:
mse_loss = nn.MSELoss()

mse_loss(x_hat, x)

tensor(0.2867)