딥러닝을 위한 수학 기초

In [1]:
n = 10
x = [i + 1 for i in range(n)]
print(x)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [2]:
#sum
n = 10
x = [i + 1 for i in range(n)]

ret = 0
for j in x:
    ret += j

print(ret)

55


In [3]:
#product

n = 10
x = [i + 1 for i in range(n)]

ret = 1
for j in x:
    ret *= j

print(ret)

3628800


In [4]:
#argmax
#최대값의 인덱스 찾기

import numpy as np

n = 10

x = [i + 1 for i in range(n)]

def f(x):
    return -np.log(x) # '-' 의미 : 값을 뒤집는다

max_val = -np.inf #음의 무한대
#어떤 값보다 작은 초기값 설정 >> 첫번째 계산값이 항상 최대값이 되도록 함

argmax = None

for j in x:
    val = f(j)
    if val > max_val:
        max_val = val
        argmax = j

print(argmax)

1


In [8]:
import torch

a = torch.FloatTensor([[1,2],
                       [3,4]])

b = torch.FloatTensor([[1, 2],
                       [1,2]])

In [9]:
print(a)
print(b)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [1., 2.]])


In [10]:
#행렬 곱
c = torch.matmul(a, b)
c

tensor([[ 3.,  6.],
        [ 7., 14.]])