# Gradient Descent

In [1]:
import torch
import torch.nn.functional as F

In [2]:
target = torch.FloatTensor([[.1, .2, .3],
                            [.4, .5, .6],
                            [.7, .8, .9]])

target

tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000],
        [0.7000, 0.8000, 0.9000]])

In [3]:
x = torch.rand_like(target)
# This means the final scalar will be differentiate by x.
x.requires_grad = True
# You can get gradient of x, after differentiation.

x

tensor([[0.0690, 0.4316, 0.8808],
        [0.8829, 0.3171, 0.9961],
        [0.0904, 0.2840, 0.8670]], requires_grad=True)

In [4]:
loss = F.mse_loss(x, target)

loss

tensor(0.1616, grad_fn=<MseLossBackward0>)

In [5]:
threshold = 1e-5
learning_rate = 1.
iter_cnt = 0

while loss > threshold:
    iter_cnt += 1
    
    loss.backward() # Calculate gradients. 미분 

    x = x - learning_rate * x.grad
    
    x.detach_()
    x.requires_grad_(True)
    
    loss = F.mse_loss(x, target)
    
    print('%d-th Loss: %.4e' % (iter_cnt, loss))
    print(x)

1-th Loss: 9.7759e-02
tensor([[0.0759, 0.3801, 0.7517],
        [0.7756, 0.3578, 0.9080],
        [0.2258, 0.3986, 0.8743]], requires_grad=True)
2-th Loss: 5.9138e-02
tensor([[0.0813, 0.3401, 0.6513],
        [0.6921, 0.3894, 0.8396],
        [0.3312, 0.4878, 0.8800]], requires_grad=True)
3-th Loss: 3.5775e-02
tensor([[0.0854, 0.3090, 0.5733],
        [0.6272, 0.4140, 0.7863],
        [0.4132, 0.5572, 0.8845]], requires_grad=True)
4-th Loss: 2.1642e-02
tensor([[0.0887, 0.2847, 0.5125],
        [0.5767, 0.4331, 0.7449],
        [0.4769, 0.6112, 0.8879]], requires_grad=True)
5-th Loss: 1.3092e-02
tensor([[0.0912, 0.2659, 0.4653],
        [0.5374, 0.4479, 0.7127],
        [0.5265, 0.6531, 0.8906]], requires_grad=True)
6-th Loss: 7.9197e-03
tensor([[0.0931, 0.2513, 0.4286],
        [0.5069, 0.4595, 0.6877],
        [0.5650, 0.6858, 0.8927]], requires_grad=True)
7-th Loss: 4.7910e-03
tensor([[0.0947, 0.2399, 0.4000],
        [0.4831, 0.4685, 0.6682],
        [0.5950, 0.7111, 0.8943]], requi