In [1]:
import torch

a = torch.FloatTensor([[1, 2],
                       [3, 4]])
b = torch.FloatTensor([[2, 2],
                       [3, 3]])

In [2]:
print(a)
print(b)


tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 2.],
        [3., 3.]])


In [3]:
a + b

tensor([[3., 4.],
        [6., 7.]])

In [4]:
a - b

tensor([[-1.,  0.],
        [ 0.,  1.]])

In [5]:
a * b

tensor([[ 2.,  4.],
        [ 9., 12.]])

In [6]:
a / b

tensor([[0.5000, 1.0000],
        [1.0000, 1.3333]])

In [7]:
a == b

tensor([[False,  True],
        [ True, False]])

In [8]:
a != b

tensor([[ True, False],
        [False,  True]])

In [9]:
a ** b

tensor([[ 1.,  4.],
        [27., 64.]])

In [ ]:
# 같은 산술 연산 수행하나 기존 텐서에 결과가 저장됨

In [11]:
print(a)
print(b)
print()
print(a.mul(b)) #a * b

tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 2.],
        [3., 3.]])

tensor([[ 2.,  4.],
        [ 9., 12.]])


In [12]:
print(a)
print(b)
print()
print(a.mul_(b)) #곱셈 연산 결과 >> tensor a에 저장됨

tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 2.],
        [3., 3.]])

tensor([[ 2.,  4.],
        [ 9., 12.]])


In [13]:
print(a)

tensor([[ 2.,  4.],
        [ 9., 12.]])


In [14]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])

In [16]:
x.sum()
x.mean()

tensor(2.5000)

In [17]:
print(x.sum(dim=0))
# 1번째 차원 (행렬의 세로축에 대해서 합 연산 수행 )

tensor([4., 6.])


In [18]:
print(x.sum(dim=1))
# 2번째 차원 (행렬의 가로축에 대해서 합 연산 수행 )

tensor([3., 7.])


In [19]:
x = torch.FloatTensor([[1, 2]])
y = torch.FloatTensor([[4, 8]])

print(x)
print(y)
print()
print(x.size())
print(y.size()) #1행 2열임을 의미 >> 첫번째 차원의 크기가 1 두번째 차원의 크기 2

tensor([[1., 2.]])
tensor([[4., 8.]])

torch.Size([1, 2])
torch.Size([1, 2])


In [20]:
z = x + y
print(z)
print(z.size())

tensor([[ 5., 10.]])
torch.Size([1, 2])


Tensor + Scalar

In [21]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])
y = 1

print(x)
print(y)

print(x.size())

tensor([[1., 2.],
        [3., 4.]])
1
torch.Size([2, 2])


In [22]:
z = x + y
print(z)
print(z.size())

tensor([[2., 3.],
        [4., 5.]])
torch.Size([2, 2])


Tensor + Vector

In [24]:
x = torch.FloatTensor([[1, 2, 3],
                       [4, 8, 9]])

print(x.size())

torch.Size([2, 3])


In [25]:
x = torch.FloatTensor([[1, 2],
                       [4, 8]])
y = torch.FloatTensor([3, 5])

print(x)
print(y)
print()
print(x.size())
print(y.size()) #단일 차원 2개의 요소를 가진 1차원 벡터

tensor([[1., 2.],
        [4., 8.]])
tensor([3., 5.])

torch.Size([2, 2])
torch.Size([2])


In [26]:
z = x + y
print(z)
print(z.size())

tensor([[ 4.,  7.],
        [ 7., 13.]])
torch.Size([2, 2])


In [29]:
x = torch.FloatTensor([[[1, 2]]])
y = torch.FloatTensor([3,
                       5])

print(x)
print(y)
print()

print(x.size())
print(y.size())

tensor([[[1., 2.]]])
tensor([3., 5.])

torch.Size([1, 1, 2])
torch.Size([2])


In [27]:
x = torch.FloatTensor([[[1, 2], [3, 4]]])
#바깥쪽 리스트가 첫번째 차원 >> 안에 몇개의 값이 들어있는지 세면 됨
print(x.size())


torch.Size([1, 2, 2])


Tensor + Tensor

In [28]:
x = torch.FloatTensor([[1, 2]])
y = torch.FloatTensor([[3],[5]])

print(x)
print(y)
print()
print(x.size())
print(y.size())

tensor([[1., 2.]])
tensor([[3.],
        [5.]])

torch.Size([1, 2])
torch.Size([2, 1])


In [31]:
x = torch.FloatTensor([[[1, 2],
                        [4, 8]]])
y = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])


print(x)
print(y)
print()
print(x.size()) # [1,2,2]
print(y.size()) # [3,3]

# z = x + y 사이즈가 안맞음

tensor([[[1., 2.],
         [4., 8.]]])
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

torch.Size([1, 2, 2])
torch.Size([3, 3])
