In [1]:
import torch



## Tensor Shaping

### reshape: Change Tensor Shape

In [2]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])
print(x)
print(x.size())

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])
torch.Size([3, 2, 2])


In [3]:
x.reshape(12)
# 12 = 3 * 2 * 2 >> 1차원

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [4]:
print(x.reshape(-1)) # -1은 1차원으로 변환함

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])


In [5]:
print(x.reshape(3, 4))
# 3 * 4 = (3 * 2 * 2) >> 2차원
print(x.reshape(3, -1))

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [6]:
print(x.reshape(3, 1, 4))
# 12 = 3*1*4 >> 3차원
print(x.reshape(-1, 1, 4))

tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])


In [7]:
print(x.reshape(3, 2, 2, 1))
# 12 = 3*2*2*1 >> 4차원
# [[[[ 1.],[ 2.]],[[ 3.],[ 4.]]],[[[ 5.],[ 6.]],[[ 7.],[ 8.]]],[[[ 9.],[10.]],[[11.],[12.]]]]


tensor([[[[ 1.],
          [ 2.]],

         [[ 3.],
          [ 4.]]],


        [[[ 5.],
          [ 6.]],

         [[ 7.],
          [ 8.]]],


        [[[ 9.],
          [10.]],

         [[11.],
          [12.]]]])


In [8]:
### squeeze: Remove dimension which has only one element.

In [9]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]]])

print(x)
print(x.size())

tensor([[[1., 2.],
         [3., 4.]]])
torch.Size([1, 2, 2])


In [10]:
# 1인 차원 제거
print(x.squeeze())
print(x.squeeze().size())


tensor([[1., 2.],
        [3., 4.]])
torch.Size([2, 2])


요소가 하나만 있는 경우 특정 차원을 제거합니다. 그렇지 않다면 아무런 변화도 없을 것입니다.

In [12]:
print(x)
print(x.squeeze(0).size())
# 0번 index '1' 존재 >> squeeze 가능
print(x.squeeze(1).size())
# 1번 index '1' 존재 하지 않음 (2임) >> squeeze 불가능

tensor([[[1., 2.],
         [3., 4.]]])
torch.Size([2, 2])
torch.Size([1, 2, 2])


### unsqueeze: 특정 인덱스에 차원을 삽입합니다.

In [20]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])

print(x)
print(x.size())

tensor([[1., 2.],
        [3., 4.]])
torch.Size([2, 2])


In [15]:
# unsqueeze() : 특정 dimension에 '1' 더함 (차원 증가)
print(x.unsqueeze(2))
# 3번째 dimension에 '1' 첨가
print(x.unsqueeze(2).size())

print(x.unsqueeze(-1))
# 마지막 dimension에 '1' 첨가
print(x.unsqueeze(-1).size())

tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
torch.Size([2, 2, 1])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
torch.Size([2, 2, 1])


In [19]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]]])
print(x.unsqueeze(2).size())

torch.Size([1, 2, 1, 2])


In [21]:
print(x.reshape(2, 2, -1))

tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
