# PyTorch Useful Methods

In [98]:
import torch

### expand: copy the given tensor and concat those at desired dimension.

In [99]:
x = torch.FloatTensor([[[1, 2]],
                       [[3, 4]]])

print(x)
print(x.size())

tensor([[[1., 2.]],

        [[3., 4.]]])
torch.Size([2, 1, 2])


In [100]:
y = x.expand(*[2, 3, 2])
# 텐서의 데이터를 반복하여 확장된 새로운 크기의 텐서를 생성

print(y)
print(y.size())

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])
torch.Size([2, 3, 2])


#### Implement expand with cat.

In [101]:
y = torch.cat([x, x, x], dim=1)

print(y)
print(y.size())

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])
torch.Size([2, 3, 2])


### randperm: Random Permutation

In [102]:
# randperm() : 랜덤 수열을 생성
x = torch.randperm(10)

print(x)
print(x.size())

tensor([6, 5, 1, 0, 9, 7, 3, 8, 4, 2])
torch.Size([10])


### argmax: Return index of maximum values

In [103]:
x = torch.randperm(3**3)
print(x)
print(x.size())

tensor([ 5, 24,  3, 13,  9,  0, 18, 17, 12,  6, 20, 10, 14, 15, 25, 21,  7,  2,
         4, 19, 22, 11, 16, 26,  1,  8, 23])
torch.Size([27])


In [104]:
x = torch.randperm(3**3).reshape(3, 3, -1)

print(x)
print(x.size())

tensor([[[ 7, 21, 18],
         [ 4, 15, 20],
         [10,  1, 17]],

        [[22, 11, 14],
         [23,  3,  2],
         [ 8, 26, 12]],

        [[ 9, 25,  6],
         [13, 16, 19],
         [24,  5,  0]]])
torch.Size([3, 3, 3])


In [105]:
# argmax() : f(X) 함수의 출력값을 최대로 만드는 입력(index) 반환 
y = x.argmax(dim=-1)

print(y)
print(y.size())

tensor([[1, 2, 2],
        [0, 0, 1],
        [1, 2, 0]])
torch.Size([3, 3])


### topk: Return tuple of top-k values and indices.

In [106]:
# topk : 가장 큰 k개의 값과 인덱스 반환 
values, indices = torch.topk(x, k=1, dim=-1)

print(values) 
print()
print(indices)
print()
print(values.size())
print(indices.size())
# torch.Size([3, 3, 1]) k=1 때문 

tensor([[[21],
         [20],
         [17]],

        [[22],
         [23],
         [26]],

        [[25],
         [19],
         [24]]])

tensor([[[1],
         [2],
         [2]],

        [[0],
         [0],
         [1]],

        [[1],
         [2],
         [0]]])

torch.Size([3, 3, 1])
torch.Size([3, 3, 1])


Note that topk didn't reduce the dimension, even in $k=1$ case.

In [107]:
print(values.squeeze(-1)) #마지막 차원이 1일경우 제거 
print(values.squeeze(-1).size())
print()
print(indices.squeeze(-1))
print(indices.squeeze(-1).size())

tensor([[21, 20, 17],
        [22, 23, 26],
        [25, 19, 24]])
torch.Size([3, 3])

tensor([[1, 2, 2],
        [0, 0, 1],
        [1, 2, 0]])
torch.Size([3, 3])


In [108]:
print(x.argmax(dim=-1) == indices.squeeze(-1))

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [109]:
_, indices = torch.topk(x, k=2, dim=-1)
print(indices.size()) 
# torch.Size([3, 3, 2]) k=2 때문 

print(x.argmax(dim=-1) == indices[:, :, 0]) 

torch.Size([3, 3, 2])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [110]:
print(indices[:, :, 0])
print(indices[:, :, 0].size())
# torch.Size([3, 3]) k=0

tensor([[1, 2, 2],
        [0, 0, 1],
        [1, 2, 0]])
torch.Size([3, 3])


### Sort by using topk

In [111]:
target_dim = -1
values, indices = torch.topk(x,
                             k=x.size(target_dim),
                             largest=True) # 내림차순
#x.size(-1) >> 마지막 차원의 크기 >> 3 
print(values)

tensor([[[21, 18,  7],
         [20, 15,  4],
         [17, 10,  1]],

        [[22, 14, 11],
         [23,  3,  2],
         [26, 12,  8]],

        [[25,  9,  6],
         [19, 16, 13],
         [24,  5,  0]]])


### Topk by using sort

In [112]:
k=1
values, indices = torch.sort(x, dim=-1, descending=True) #내림차순

print(values)
print(indices)

tensor([[[21, 18,  7],
         [20, 15,  4],
         [17, 10,  1]],

        [[22, 14, 11],
         [23,  3,  2],
         [26, 12,  8]],

        [[25,  9,  6],
         [19, 16, 13],
         [24,  5,  0]]])
tensor([[[1, 2, 0],
         [2, 1, 0],
         [2, 0, 1]],

        [[0, 2, 1],
         [0, 1, 2],
         [1, 2, 0]],

        [[1, 0, 2],
         [2, 1, 0],
         [0, 1, 2]]])


In [113]:
print(values[:,:,:1])
print(values[:,:,:1].size())

tensor([[[21],
         [20],
         [17]],

        [[22],
         [23],
         [26]],

        [[25],
         [19],
         [24]]])
torch.Size([3, 3, 1])


In [114]:
values, indices = values[:, :, :k], indices[:, :, :k] 
# k=1 >> values[:,:, :1] >> 각 행렬의 0번째 열 ~ (k-1)열까지 선택 
# k=1 >> 0번째 열만 선택 

print(values)
print(indices)

print(values.size()) # (3,3,1) >> 각 행렬의 첫번째 열만 포함 
print(indices.size())

tensor([[[21],
         [20],
         [17]],

        [[22],
         [23],
         [26]],

        [[25],
         [19],
         [24]]])
tensor([[[1],
         [2],
         [2]],

        [[0],
         [0],
         [1]],

        [[1],
         [2],
         [0]]])
torch.Size([3, 3, 1])
torch.Size([3, 3, 1])


In [122]:
print(values.squeeze(-1))
print(indices.squeeze(-1))

print(values.squeeze(-1).size())
print(indices.squeeze(-1).size())

tensor([[21, 20, 17],
        [22, 23, 26],
        [25, 19, 24]])
tensor([[1, 2, 2],
        [0, 0, 1],
        [1, 2, 0]])
torch.Size([3, 3])
torch.Size([3, 3])


### masked_fill: fill the value if element of mask is True.

In [126]:
# 텐서 내 원하는 부분만 특정 값으로 바꾸기  

In [123]:
torch.FloatTensor([i for i in range(3**2)])

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [124]:
x = torch.FloatTensor([i for i in range(3**2)]).reshape(3, -1) # 3 * ? = 9

print(x)
print(x.size())

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
torch.Size([3, 3])


In [125]:
mask = x > 4

print(mask)

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])


In [127]:
y = x.masked_fill(mask, value=-1)
# 주어진 마스크 텐서가 True인 위치를 지정된 값으로 채움
print(y)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4., -1.],
        [-1., -1., -1.]])


### Ones and Zeros

In [128]:
print(torch.ones(2, 3))
print(torch.zeros(2, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [129]:
x = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6]])

print(x)
print(x.size())

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])


In [130]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
